### ISSUE TITLE
Incorrect dimensions (leading to misleading performance)

### ISSUE THREAD

**Issue by shaneh2** [beld/Tensorflow-seq2seq-autoencoder#1]
Hi,

In `Tensorflow-seq2seq-autoencoder/simple_seq2seq_autoencoder.py` , the code runs and training converges for me, but I think it isn't implementing the LSTM autoencoder properly:

I notice that encoder_inputs is a list of length 1, containing a reference to a Tensorflow tensor object of shape `(10,3) = (size (of the hidden layer),frame_dim)`.

`help(tf.nn.rnn)` says that input is assumed to be a list of length T, where each element is a reference to a Tensorflow tensor of shape `[batch_size x cell.state_size]`.

`tf.nn.rnn` may see this as a sequence of length 1, where the batch size is 10 and the frame dimension is 3.

Another approach may involve 
`encoder_inputs = tf.unpack(seq_input)`

Here is a sketch of my attempt to fix this. It has a few other unrelated changes, sorry about that..

```

# if encoder input is "X, Y, Z", then decoder input is "0, X, Y, Z". Therefore, the decoder size
# and target size equal encoder size plus 1. For simplicity, here I droped the last one.
encoder_inputs_unpacked=tf.unpack(encoder_inputs)
decoder_inputs = ([tf.zeros_like(encoder_inputs_unpacked[0], name="GO")] + encoder_inputs_unpacked[:-1])

targets = desired_outputs
weights = [tf.ones_like(targets_t, dtype=tf.float32) for targets_t in tf.unpack(targets)]

# basic LSTM seq2seq model
cell = tf.nn.rnn_cell.GRUCell(size)
enc_output, enc_state = tf.nn.dynamic_rnn(cell, encoder_inputs, dtype=tf.float32, time_major=True)
enc_state=tf.nn.dropout(keep_prob=0.8,x=enc_state)
enc_state_unpacked=tf.unpack(enc_state,num=n_steps)

if makeHiddenLayerBinary:
    enc_state=tf.nn.sigmoid(enc_state)

cell_to_reconstruction = tf.nn.rnn_cell.OutputProjectionWrapper(cell, frame_dim)
dec_outputs, dec_state = tf.nn.seq2seq.rnn_decoder(decoder_inputs, enc_state, cell_to_reconstruction)
# e_stop = np.array([1, 1])

```

**Comment by beld** [comment]
Hi @shaneh2,
Yes, using tf.unpack() is a better way to directly feed the encoder input if the batch_size is known and fixed. You can declared the encoder input as a tensor with a shape of [rnn_timesteps, batch_size, feature_dims] and unpack this tensor into a list of 2D tensor with the shape of [batch_size, feature_dims].

When the batch_size is not fixed and adjustable, you probably want to declare the encoder input in the way that official seq2seq model does.

```
self.encoder_inputs = []
for i in xrange(buckets[-1][0]):  # Last bucket is the biggest one.
    self.encoder_inputs.append(tf.placeholder(tf.int32, shape=[None], name="encoder{0}".format(i)))
```

here None refers to the unfixed batch size. Notice that the encoder input of official seq2seq model is a list of 1D tensor, not 2D in this simple script where we can has feature_dims.
